import Head from 'next/head';
import Navbar from '../components/Navbar';
import Sidebar from '../components/Sidebar';
import { useState } from 'react';
import Table from '../components/Table';
import Charts from '../components/Charts';

export default function Home() {
  const [isOpen, setIsOpen] = useState(null);

  return (
    <main>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar isOpen={isOpen} setIsOpen={setIsOpen} />
      <Sidebar isOpen={isOpen} />

      <section className="px-4 py-8 md:p-12 sm:ml-64 min-h-screen">
        <div className="py-12 grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
          <Table />
        </div>
      </section>
    </main>
  );
}
