import Head from 'next/head';
import supabaseUser from '../lib/useSupabaseUser';
import Navbar from '../components/Navbar';
import Sidebar from '../components/Sidebar';
import { useState } from 'react';

export default function Home() {
  const { user } = supabaseUser();
  const [isOpen, setIsOpen] = useState(null);

  return (
    <div>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar isOpen={isOpen} setIsOpen={setIsOpen} />
      <Sidebar isOpen={isOpen} />

      <main className="p-12 sm:ml-64">
        <div className="p-4 border-2 border-gray-200 border-dashed rounded-lg dark:border-gray-700 mt-14 flex flex-col md:flex-row justify-between md:items-center">
          <p className="font-bold text-sm">
            <span className="font-normal">User</span>:{' '}
            {user?.user_metadata?.address}
          </p>
        </div>
      </main>
    </div>
  );
}
