import Head from 'next/head';
import React, { useState } from 'react';
import Navbar from '../components/Navbar';
import Sidebar from '../components/Sidebar';
import { v4 as uuidv4 } from 'uuid';
import { useContract, useContractWrite } from '@thirdweb-dev/react';

const Patient = () => {
  const [isOpen, setIsOpen] = useState(null);
  const [formData, setFormData] = useState({
    nama: '',
    asuransi: '',
    tempatLahir: '',
    tanggalLahir: '',
    nomorTelpon: '',
    poliklinik: '',
    tanggalBerobat: '',
    jk: '',
    dokter: '',
    diagnosa: '',
  });

  const { contract } = useContract(
    '0x388f2AEDcdA3A4b362424df5729a8A51c1A079A7'
  );
  const { mutateAsync: addMedicalRecord, isLoading } = useContractWrite(
    contract,
    'addMedicalRecord'
  );

  const handleSubmit = async (e) => {
    e.preventDefault();

    try {
      await addMedicalRecord({
        args: [
          uuidv4(),
          formData.nama,
          formData.asuransi,
          formData.tempatLahir,
          new Date(formData.tanggalLahir).getTime(),
          formData.nomorTelpon,
          formData.poliklinik,
          new Date(formData.tanggalBerobat).getTime(),
          formData.jk,
          formData.dokter,
          formData.diagnosa,
        ],
      });
    } catch (error) {
      console.error('contract call failure', error);
    }
  };

  return (
    <main>
      <Head>
        <title>Patients page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar isOpen={isOpen} setIsOpen={setIsOpen} />
      <Sidebar isOpen={isOpen} />

      <section className="px-4 py-8 md:p-12 sm:ml-64 min-h-screen">
        <div className="py-16 md:py-12">
          <h1 className="text-3xl mb-8 font-semibold text-indigo-500">
            Create Patient
          </h1>

          <form
            className="flex flex-col gap-6 md:gap-12"
            onSubmit={handleSubmit}
          >
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div class="relative z-0">
                <input
                  type="text"
                  id="nama"
                  value={formData.nama}
                  onChange={(e) =>
                    setFormData({ ...formData, nama: e.target.value })
                  }
                  class="block py-2.5 px-0 w-full text-sm text-gray-300 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer"
                  placeholder=" "
                />
                <label
                  for="nama"
                  class="absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6"
                >
                  Pasien
                </label>
              </div>

              <div class="relative z-0">
                <input
                  type="text"
                  id="asuransi"
                  value={formData.asuransi}
                  onChange={(e) =>
                    setFormData({ ...formData, asuransi: e.target.value })
                  }
                  class="block py-2.5 px-0 w-full text-sm text-gray-300 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer"
                  placeholder=" "
                />
                <label
                  for="asuransi"
                  class="absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6"
                >
                  Nomor asuransi
                </label>
              </div>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
              <div class="relative z-0">
                <input
                  type="text"
                  id="tempat_lahir"
                  value={formData.tempatLahir}
                  onChange={(e) =>
                    setFormData({ ...formData, tempatLahir: e.target.value })
                  }
                  class="block py-2.5 px-0 w-full text-sm text-gray-300 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer"
                  placeholder=" "
                />
                <label
                  for="tempat_lahir"
                  class="absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6"
                >
                  Tempat Lahir
                </label>
              </div>

              <div class="relative z-0">
                <input
                  type="date"
                  id="tgl_lahir"
                  onChange={(e) =>
                    setFormData({ ...formData, tanggalLahir: e.target.value })
                  }
                  class="block py-2.5 px-0 w-full text-sm text-gray-300 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer"
                  placeholder=" "
                />
                <label
                  for="tgl_lahir"
                  class="absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6"
                >
                  Tanggal lahir
                </label>
              </div>

              <div class="relative z-0">
                <input
                  type="text"
                  pattern="[0-9]+"
                  id="no_telp"
                  value={formData.nomorTelpon}
                  onChange={(e) =>
                    setFormData({ ...formData, nomorTelpon: e.target.value })
                  }
                  class="block py-2.5 px-0 w-full text-sm text-gray-300 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer"
                  placeholder=" "
                />
                <label
                  for="no_telp"
                  class="absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6"
                >
                  No Telpon
                </label>
              </div>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div class="relative z-0">
                <input
                  type="text"
                  id="poliklinik"
                  value={formData.poliklinik}
                  onChange={(e) =>
                    setFormData({ ...formData, poliklinik: e.target.value })
                  }
                  class="block py-2.5 px-0 w-full text-sm text-gray-300 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer"
                  placeholder=" "
                />
                <label
                  for="poliklinik"
                  class="absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6"
                >
                  Poli Rawat
                </label>
              </div>

              <div class="relative z-0">
                <input
                  type="date"
                  id="berobat"
                  value={formData.tanggalBerobat}
                  onChange={(e) =>
                    setFormData({ ...formData, tanggalBerobat: e.target.value })
                  }
                  class="block py-2.5 px-0 w-full text-sm text-gray-300 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer"
                  placeholder=" "
                />
                <label
                  for="berobat"
                  class="absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6"
                >
                  Tanggal berobat
                </label>
              </div>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div class="flex items-center justify-center gap-4">
                <div class="flex items-center mr-4">
                  <input
                    id="pria"
                    type="radio"
                    value="laki-laki"
                    onChange={(e) =>
                      setFormData({ ...formData, jk: e.target.value })
                    }
                    name="colored-radio"
                    class="w-4 h-4 text-purple-600 focus:ring-purple-600 ring-offset-gray-800 focus:ring-2 bg-gray-700 border-gray-600"
                  />
                  <label
                    for="pria"
                    class="ml-2 text-sm font-medium text-gray-100"
                  >
                    Laki-laki
                  </label>
                </div>

                <div class="flex items-center mr-4">
                  <input
                    id="wanita"
                    type="radio"
                    value="perempuan"
                    onChange={(e) =>
                      setFormData({ ...formData, jk: e.target.value })
                    }
                    name="colored-radio"
                    class="w-4 h-4 text-purple-600 focus:ring-purple-600 ring-offset-gray-800 focus:ring-2 bg-gray-700 border-gray-600"
                  />
                  <label
                    for="wanita"
                    class="ml-2 text-sm font-medium text-gray-100"
                  >
                    Perempuan
                  </label>
                </div>
              </div>

              <div class="relative z-0">
                <input
                  type="text"
                  id="dokter"
                  value={formData.dokter}
                  onChange={(e) =>
                    setFormData({ ...formData, dokter: e.target.value })
                  }
                  class="block py-2.5 px-0 w-full text-sm text-gray-300 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer"
                  placeholder=" "
                />
                <label
                  for="dokter"
                  class="absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6"
                >
                  Dokter
                </label>
              </div>
            </div>

            <div className="flex flex-col gap-2">
              <label
                for="message"
                class="block mb-2 text-sm font-medium text-gray-500"
              >
                Diagnosa
              </label>
              <textarea
                id="message"
                rows="4"
                onChange={(e) =>
                  setFormData({ ...formData, diagnosa: e.target.value })
                }
                class="block p-2.5 w-full text-sm rounded-lg border bg-gray-700 border-gray-600 placeholder-gray-400 text-white focus:ring-blue-500 focus:border-blue-500"
                placeholder="Diagnosa berdasarkan yang dirasakan pasien..."
              ></textarea>
            </div>

            <div className="flex items-center justify-end">
              <button
                type="submit"
                class="text-white bg-gradient-to-br from-purple-600 to-blue-500 hover:bg-gradient-to-bl focus:ring-4 focus:outline-none focus:ring-blue-300 dark:focus:ring-blue-800 w-full sm:w-auto font-medium rounded-lg px-7 py-1.5 text-center"
              >
                Create
              </button>
            </div>
          </form>
        </div>
      </section>
    </main>
  );
};

export default Patient;
